"""SE2CAD library surface.

S2C-1.2.1 exposes the blueprint parser. S2C-2.1.1 exposes the definition
catalog. S2C-3.1.1 exposes the CAD-neutral IR and placement transforms.
S2C-4.1.1 exposes the canonical block-library recipes. S2C-7.1.1 exposes
CAD-neutral blueprint statistics. S2C-8.1.1 exposes CAD-neutral
component names from IR fields. S2C-9.1.1 carries CAD-neutral
``ColorMaskHSV`` appearance on the parser and IR. The SolidWorks
backend lives in ``se2cad.solidworks`` and is not imported here.
"""

from se2cad.catalog import (
    LARGE_GRID_CELL_PITCH_MM,
    CatalogEntry,
    CatalogError,
    CatalogValidationError,
    CellSize,
    DefinitionCatalog,
    ObservedDefinition,
    RecipeKind,
    SupportStatus,
    UnknownSubtypeError,
    load_default_catalog,
)
from se2cad.ir import (
    COMPONENT_NAME_MAX_LENGTH,
    CanonicalBlock,
    CanonicalBlueprint,
    CanonicalGrid,
    ComponentNameError,
    IrError,
    build_canonical_blueprint,
    component_name,
    component_name_from_block,
    component_names_from_blocks,
)
from se2cad.library import (
    CANONICAL_CELL_ENVELOPE,
    CANONICAL_LOCAL_FRAME,
    LibraryError,
    LibraryRecord,
    NativeSolidRecipe,
    SolidKind,
    UnknownGeometryError,
    all_library_records,
    cell_half_extent_mm,
    lookup_recipe,
    lookup_record,
)
from se2cad.parser import (
    DEFAULT_COLOR_MASK_HSV,
    AppearanceSupport,
    BlueprintParseError,
    ColorMaskHSV,
    Direction,
    GridCoordinate,
    GridSize,
    InvalidFieldError,
    MalformedXmlError,
    MissingRequiredFieldError,
    ParsedBlock,
    ParsedBlueprint,
    ParsedGrid,
    UnsupportedBlueprintError,
    parse_blueprint,
    parse_blueprint_xml,
)
from se2cad.statistics import (
    AxisRange,
    BlueprintStatistics,
    CatalogCoverage,
    CellExtents,
    MillimetreSize,
    NamedCount,
    Occupancy,
    OrientationCount,
    compute_blueprint_statistics,
    compute_blueprint_statistics_from_path,
    compute_blueprint_statistics_from_xml,
)
from se2cad.transform import (
    IDENTITY_ROTATION,
    SE_DIRECTION_VECTORS,
    InvalidOrientationError,
    MillimetrePosition,
    RotationMatrix,
    TransformError,
    cell_center_mm,
    direction_vector,
    is_valid_orientation,
    legal_orientations,
    rotation_from_forward_up,
)

__all__ = [
    "CANONICAL_CELL_ENVELOPE",
    "CANONICAL_LOCAL_FRAME",
    "COMPONENT_NAME_MAX_LENGTH",
    "DEFAULT_COLOR_MASK_HSV",
    "IDENTITY_ROTATION",
    "LARGE_GRID_CELL_PITCH_MM",
    "SE_DIRECTION_VECTORS",
    "AppearanceSupport",
    "AxisRange",
    "BlueprintParseError",
    "BlueprintStatistics",
    "CanonicalBlock",
    "CanonicalBlueprint",
    "CanonicalGrid",
    "CatalogCoverage",
    "CatalogEntry",
    "CatalogError",
    "CatalogValidationError",
    "CellExtents",
    "CellSize",
    "ColorMaskHSV",
    "ComponentNameError",
    "DefinitionCatalog",
    "Direction",
    "GridCoordinate",
    "GridSize",
    "InvalidFieldError",
    "InvalidOrientationError",
    "IrError",
    "LibraryError",
    "LibraryRecord",
    "MalformedXmlError",
    "MillimetrePosition",
    "MillimetreSize",
    "MissingRequiredFieldError",
    "NamedCount",
    "NativeSolidRecipe",
    "Occupancy",
    "ObservedDefinition",
    "OrientationCount",
    "ParsedBlock",
    "ParsedBlueprint",
    "ParsedGrid",
    "RecipeKind",
    "RotationMatrix",
    "SolidKind",
    "SupportStatus",
    "TransformError",
    "UnknownGeometryError",
    "UnknownSubtypeError",
    "UnsupportedBlueprintError",
    "all_library_records",
    "build_canonical_blueprint",
    "cell_center_mm",
    "cell_half_extent_mm",
    "component_name",
    "component_name_from_block",
    "component_names_from_blocks",
    "compute_blueprint_statistics",
    "compute_blueprint_statistics_from_path",
    "compute_blueprint_statistics_from_xml",
    "direction_vector",
    "is_valid_orientation",
    "legal_orientations",
    "load_default_catalog",
    "lookup_recipe",
    "lookup_record",
    "parse_blueprint",
    "parse_blueprint_xml",
    "rotation_from_forward_up",
]
